 const bookArchive = [
  {
    id: 1,
    formato: "Libro",
    pnf: "Informatica",
    materia: "Matematica",
    nombre: "Metodología de investigación Para qué",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "metodologia_de_la_investigacion_para_que.PNG",
    link: "https://drive.google.com/file/d/18WUR4_UE2DB5z7hdtbVg21fOwY0Pgmqh/view?usp=sharing",
  },
  {
    id: 2,
    formato: "revista",
    pnf: "Informatica",
    materia: "Matematica",
    nombre: "Metodología de investigación 4 edicion",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "metodologia_de_la_investigacion_4.PNG",
    link: "https://drive.google.com/file/d/1ag9qWOdxXLB5aMz8MK6Gs7u8w-tCmk0w/view?usp=sharing",
  },
  {
    id: 3,
    formato: "libro",
    pnf: "Informatica",
    materia: "Matematica",
    nombre: "a Metodología de investigación Para qué",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "metodologia_de_la_investigacion_para_que.PNG",
    link: "https://drive.google.com/file/d/18WUR4_UE2DB5z7hdtbVg21fOwY0Pgmqh/view?usp=sharing",
  },
  {
    id: 4,
    formato: "libro",
    PNF: "Informatica",
    materia: "Matematica",
    nombre: "b Metodología de investigación 4 edicion",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "metodologia_de_la_investigacion_4.PNG",
    link: "https://drive.google.com/file/d/1ag9qWOdxXLB5aMz8MK6Gs7u8w-tCmk0w/view?usp=sharing",
  },
  {
    id: 5,
    formato: "libro",
    PNF: "Informatica",
    materia: "Matematica",
    nombre: "investigación Para qué",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "metodologia_de_la_investigacion_para_que.PNG",
    link: "https://drive.google.com/file/d/18WUR4_UE2DB5z7hdtbVg21fOwY0Pgmqh/view?usp=sharing",
  },
  {
    id: 6,
    formato: "libro",
    PNF: "Informatica",
    materia: "Programacion",
    nombre: "Humano demaciado humano",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "metodologia_de_la_investigacion_4.PNG",
    link: "https://drive.google.com/file/d/1ag9qWOdxXLB5aMz8MK6Gs7u8w-tCmk0w/view?usp=sharing",
  },
  {
    id: 7,
    formato: "libro",
    PNF: "Informatica",
    materia: "Programacion",
    nombre: "Metodología de investigación Para qué",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "metodologia_de_la_investigacion_para_que.PNG",
    link: "https://drive.google.com/file/d/18WUR4_UE2DB5z7hdtbVg21fOwY0Pgmqh/view?usp=sharing",
  },
  {
    id: 8,
    formato: "libro",
    PNF: "Informatica",
    materia: "Programacion",
    nombre: "Metodología de investigación 4 edicion",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "metodologia_de_la_investigacion_4.PNG",
    link: "https://drive.google.com/file/d/1ag9qWOdxXLB5aMz8MK6Gs7u8w-tCmk0w/view?usp=sharing",
  },
  {
    id: 9,
    formato: "libro",
    PNF: "Informatica",
    materia: "Programacion",
    nombre: "Metodología de investigación Para qué",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "metodologia_de_la_investigacion_para_que.PNG",
    link: "https://drive.google.com/file/d/18WUR4_UE2DB5z7hdtbVg21fOwY0Pgmqh/view?usp=sharing",
  },
  {
    id: 10,
    formato: "libro",
    PNF: "Informatica",
    materia: "Programacion",
    nombre: "Metodología de investigación 4 edicion",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "metodologia_de_la_investigacion_4.PNG",
    link: "https://drive.google.com/file/d/1ag9qWOdxXLB5aMz8MK6Gs7u8w-tCmk0w/view?usp=sharing",
  },
  {
    id: 11,
    formato: "libro",
    PNF: "Informatica",
    materia: "Proyecto",
    nombre: "Metodología de investigación Para qué",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "metodologia_de_la_investigacion_para_que.PNG",
    link: "https://drive.google.com/file/d/18WUR4_UE2DB5z7hdtbVg21fOwY0Pgmqh/view?usp=sharing",
  },
  {
    id: 12,
    formato: "libro",
    PNF: "Informatica",
    materia: "Proyecto",
    nombre: "Metodología de investigación 4 edicion",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "metodologia_de_la_investigacion_4.PNG",
    link: "https://drive.google.com/file/d/1ag9qWOdxXLB5aMz8MK6Gs7u8w-tCmk0w/view?usp=sharing",
  },
  {
    id: 13,
    formato: "libro",
    PNF: "Informatica",
    materia: "Proyecto",
    nombre: "Metodología de investigación Para qué",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "metodologia_de_la_investigacion_para_que.PNG",
    link: "https://drive.google.com/file/d/18WUR4_UE2DB5z7hdtbVg21fOwY0Pgmqh/view?usp=sharing",
  },
  {
    id: 14,
    formato: "libro",
    PNF: "Informatica",
    materia: "Proyecto",
    nombre: "Metodología de investigación 4 edicion",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "metodologia_de_la_investigacion_4.PNG",
    link: "https://drive.google.com/file/d/1ag9qWOdxXLB5aMz8MK6Gs7u8w-tCmk0w/view?usp=sharing",
  },
  {
    id: 15,
    formato: "libro",
    PNF: "Informatica",
    materia: "Proyecto",
    nombre: "Metodología de investigación Para qué",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "metodologia_de_la_investigacion_para_que.PNG",
    link: "https://drive.google.com/file/d/18WUR4_UE2DB5z7hdtbVg21fOwY0Pgmqh/view?usp=sharing",
  },
  {
    id: 16,
    formato: "libro",
    PNF: "Informatica",
    materia: "Proyecto",
    nombre: "Metodología de investigación Para qué",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "metodologia_de_la_investigacion_para_que.PNG",
    link: "https://drive.google.com/file/d/18WUR4_UE2DB5z7hdtbVg21fOwY0Pgmqh/view?usp=sharing",
  },
  {
    id: 17,
    formato: "libro",
    PNF: "Informatica",
    materia: "Proyecto",
    nombre: "Metodología de investigación Para qué",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "metodologia_de_la_investigacion_para_que.PNG",
    link: "https://drive.google.com/file/d/18WUR4_UE2DB5z7hdtbVg21fOwY0Pgmqh/view?usp=sharing",
  },
  {
    id: 18,
    formato: "libro",
    PNF: "Informatica",
    materia: "Proyecto",
    nombre: "Metodología de investigación Para qué",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "metodologia_de_la_investigacion_para_que.PNG",
    link: "https://drive.google.com/file/d/18WUR4_UE2DB5z7hdtbVg21fOwY0Pgmqh/view?usp=sharing",
  },
  {
    id: 19,
    formato: "libro",
    PNF: "Informatica",
    materia: "Proyecto",
    nombre: "Metodología de investigación Para qué",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "metodologia_de_la_investigacion_para_que.PNG",
    link: "https://drive.google.com/file/d/18WUR4_UE2DB5z7hdtbVg21fOwY0Pgmqh/view?usp=sharing",
  },
  {
    id: 20,
    formato: "libro",
    PNF: "Informatica",
    materia: "Proyecto",
    nombre: "Metodología de investigación Para qué",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "metodologia_de_la_investigacion_para_que.PNG",
    link: "https://drive.google.com/file/d/18WUR4_UE2DB5z7hdtbVg21fOwY0Pgmqh/view?usp=sharing",
  },
  {
    id: 21,
    formato: "libro",
    PNF: "Informatica",
    materia: "Proyecto",
    nombre: "Metodología de investigación Para qué",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "metodologia_de_la_investigacion_para_que.PNG",
    link: "https://drive.google.com/file/d/18WUR4_UE2DB5z7hdtbVg21fOwY0Pgmqh/view?usp=sharing",
  },
  {
    id: 22,
    formato: "libro",
    PNF: "Informatica",
    materia: "Proyecto",
    nombre: "Metodología de investigación Para qué",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "metodologia_de_la_investigacion_para_que.PNG",
    link: "https://drive.google.com/file/d/18WUR4_UE2DB5z7hdtbVg21fOwY0Pgmqh/view?usp=sharing",
  },
  {
    id: 23,
    formato: "libro",
    PNF: "Informatica",
    materia: "Proyecto",
    nombre: "Metodología de investigación Para qué",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "metodologia_de_la_investigacion_para_que.PNG",
    link: "https://drive.google.com/file/d/18WUR4_UE2DB5z7hdtbVg21fOwY0Pgmqh/view?usp=sharing",
  },
  {
    id: 24,
    formato: "libro",
    PNF: "Informatica",
    materia: "Proyecto",
    nombre: "Metodología de investigación Para qué",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "metodologia_de_la_investigacion_para_que.PNG",
    link: "https://drive.google.com/file/d/18WUR4_UE2DB5z7hdtbVg21fOwY0Pgmqh/view?usp=sharing",
  },
  {
    id: 25,
    formato: "libro",
    PNF: "Informatica",
    materia: "Proyecto",
    nombre: "Metodología de investigación Para qué",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "metodologia_de_la_investigacion_para_que.PNG",
    link: "https://drive.google.com/file/d/18WUR4_UE2DB5z7hdtbVg21fOwY0Pgmqh/view?usp=sharing",
  },
  {
    id: 26,
    formato: "libro",
    PNF: "Informatica",
    materia: "Proyecto",
    nombre: "Metodología de investigación Para qué",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "metodologia_de_la_investigacion_para_que.PNG",
    link: "https://drive.google.com/file/d/18WUR4_UE2DB5z7hdtbVg21fOwY0Pgmqh/view?usp=sharing",
  },
  {
    id: 27,
    formato: "libro",
    PNF: "Informatica",
    materia: "Proyecto",
    nombre: "Metodología de investigación Para qué",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "metodologia_de_la_investigacion_para_que.PNG",
    link: "https://drive.google.com/file/d/18WUR4_UE2DB5z7hdtbVg21fOwY0Pgmqh/view?usp=sharing",
  },
  {
    id: 28,
    formato: "libro",
    PNF: "Informatica",
    materia: "Proyecto",
    nombre: "Metodología de investigación Para qué",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "metodologia_de_la_investigacion_para_que.PNG",
    link: "https://drive.google.com/file/d/18WUR4_UE2DB5z7hdtbVg21fOwY0Pgmqh/view?usp=sharing",
  },
  {
    id: 29,
    formato: "libro",
    PNF: "Informatica",
    materia: "Proyecto",
    nombre: "Metodología de investigación Para qué",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "metodologia_de_la_investigacion_para_que.PNG",
    link: "https://drive.google.com/file/d/18WUR4_UE2DB5z7hdtbVg21fOwY0Pgmqh/view?usp=sharing",
  },
  {
    id: 30,
    formato: "libro",
    PNF: "Informatica",
    materia: "Proyecto",
    nombre: "Metodología de investigación Para qué",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "metodologia_de_la_investigacion_para_que.PNG",
    link: "https://drive.google.com/file/d/18WUR4_UE2DB5z7hdtbVg21fOwY0Pgmqh/view?usp=sharing",
  },
  {
    id: 31,
    formato: "libro",
    PNF: "Informatica",
    materia: "Proyecto",
    nombre: "Metodología de investigación Para qué",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "metodologia_de_la_investigacion_para_que.PNG",
    link: "https://drive.google.com/file/d/18WUR4_UE2DB5z7hdtbVg21fOwY0Pgmqh/view?usp=sharing",
  },
  {
    id: 32,
    formato: "libro",
    PNF: "Informatica",
    materia: "Proyecto",
    nombre: "Metodología de investigación Para qué",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "metodologia_de_la_investigacion_para_que.PNG",
    link: "https://drive.google.com/file/d/18WUR4_UE2DB5z7hdtbVg21fOwY0Pgmqh/view?usp=sharing",
  },
  {
    id: 33,
    formato: "libro",
    PNF: "Informatica",
    materia: "Proyecto",
    nombre: "Metodología de investigación Para qué",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "metodologia_de_la_investigacion_para_que.PNG",
    link: "https://drive.google.com/file/d/18WUR4_UE2DB5z7hdtbVg21fOwY0Pgmqh/view?usp=sharing",
  },
];