
export const bookArchive = [
    {
      id: 1,
      formato: "Libro",
      pnf: "Informatica",
      materia: "Matematica",
      nombre: "Metodología de investigación Para qué",
      desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
      img: "https://raw.githubusercontent.com/ViktorChs/Blioteca-de-IUTM/Mastes0.2/metodologia_de_la_investigacion_4.PNG",
      link: "https://drive.google.com/file/d/18WUR4_UE2DB5z7hdtbVg21fOwY0Pgmqh/view?usp=sharing",
    },
    {
      id: 2,
      formato: "revista",
      pnf: "Informatica",
      materia: "Matematica",
      nombre: "Metodología de investigación 4 edicion",
      desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
      img: "https://raw.githubusercontent.com/ViktorChs/Blioteca-de-IUTM/Mastes0.2/metodologia_de_la_investigacion_para_que.PNG",
      link: "https://drive.google.com/file/d/1ag9qWOdxXLB5aMz8MK6Gs7u8w-tCmk0w/view?usp=sharing",
    },
    {
      id: 3,
      formato: "libro",
      pnf: "Informatica",
      materia: "Matematica",
      nombre: "a Metodología de investigación Para qué",
      desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
      img: "https://raw.githubusercontent.com/ViktorChs/Blioteca-de-IUTM/Mastes0.2/metodologia_de_la_investigacion_4.PNG",
      link: "https://drive.google.com/file/d/18WUR4_UE2DB5z7hdtbVg21fOwY0Pgmqh/view?usp=sharing",
    },
    {
      id: 4,
      formato: "libro",
      PNF: "Informatica",
      materia: "Matematica",
      nombre: "b Metodología de investigación 4 edicion",
      desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
      img: "https://raw.githubusercontent.com/ViktorChs/Blioteca-de-IUTM/Mastes0.2/metodologia_de_la_investigacion_para_que.PNG",
      link: "https://drive.google.com/file/d/1ag9qWOdxXLB5aMz8MK6Gs7u8w-tCmk0w/view?usp=sharing",
    },
    {
      id: 5,
      formato: "libro",
      PNF: "Informatica",
      materia: "Matematica",
      nombre: "investigación Para qué",
      desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
      img: "https://raw.githubusercontent.com/ViktorChs/Blioteca-de-IUTM/Mastes0.2/metodologia_de_la_investigacion_4.PNG",
      link: "https://drive.google.com/file/d/18WUR4_UE2DB5z7hdtbVg21fOwY0Pgmqh/view?usp=sharing",
    }]
    